### ISSUE TITLE
Error: SQLSTATE[HY000] [2002] Connection timed outDB_AUTH ERROR

### ISSUE THREAD

**Issue by yvangodard** [jppo/OSSEC-GUI#1]
Bonjour, bravo pour avoir repris la suite d'analogi.
Mais j'ai de mon côté un souci.
Ma config : Ubuntu Serve 18.04 + Php 7.2 + MariaDB.
Je butte à l'installation sur une erreur SQLSTATE[HY000] [2002] Connection timed outDB_AUTH ERROR.
Evidemment, j'ai testé directement l'appel de db_ossec.php, et ce n'est donc pas un souci de paramètres SQL.
Et je n'ai rien qui sorte dans les logs pour m'aiguiller.
Au besoin, mon phpinfo avec le test de connexion à la base SQL : https://analogi.bureau.reseauenscene.fr/phpinfo.php
Et l'index de l'OSSEC-GUI https://analogi.bureau.reseauenscene.fr/index.php
Une idée d'où pourrait se cacher le problème ?

**Comment by jppo** [comment]
Bonjour,
Je suis en congés et je manque un peu d'éléments de réponse ... 
Pouvez-vous me faire parvenir une copie du schéma de la base (show tables) ainsi que la version exacte de Mysql que vous utilisez afin de m'aider à y voir clair.

Cordialement

JP Pozzi

**Comment by jppo** [comment]
Re bonjour,

En examinant les résultats de Phpinfo je vois que vous avez beaucoup d'extensions activées et que vous utilisez php 7.2, j'en suis resté au 7.0 !
Je continue à chercher.

Cordialement 
JP Pozzi

**Comment by jppo** [comment]
Re bonjour,

J'ai chargé le logiciel dans mon portable et ici, tout fonctionne, y compris le mode historique.
Je me demande pourquoi cette erreur de time_out sur la base d'authenticifation.
Avez-vous essayé en bypassant l'authentification : "ln -sf amilogged.php_noauth amilogged.php.
Cordialement
JP Pozzi

**Comment by jppo** [comment]
Je reste àvotre disposition pour vous aider a faire fonctionner au mieux le logiciel.
Pour que les affichages fonctionnent parfaitement il faut notament que toutes les alertes
aient une signature enregistrée (un trigger crée les "manquants" pour les nouvelles alertes) et
que les signatures soient bien "mappées" vers une catégorie.
Cordialement
JP P

**Comment by jppo** [comment]
Pas de nouvelles, à réouvrir si besoin
