### ISSUE TITLE
MySQL configuration

### ISSUE THREAD

**Issue by K-razy** [jppo/OSSEC-GUI#2]
Hello, I replaced data in "db_ossec.php" file.
But when loading the web page it ends with : 

Error: SQLSTATE[HY000] [2002] Connection timed outDB_AUTH ERROR

Tried in Debian 9, with Mariadb 10.1 : same result 
Tried in Debian 10, with Mariadb 10.3 : same result

Do You have any idea ?
Thanks a lot

**Comment by jppo** [comment]
Hello, 

Could you send me the file ? 

Regards 

JP Pozzi 


De: "Yvan GODARD" <notifications@github.com> 
À: "jppo/OSSEC-GUI" <OSSEC-GUI@noreply.github.com> 
Cc: "Subscribed" <subscribed@noreply.github.com> 
Envoyé: Samedi 28 Mars 2020 21:54:24 
Objet: [jppo/OSSEC-GUI] MySQL configuration (#2) 





Hello, I replaced data in "db_ossec.php" file. 
But when loading the web page it ends with : 

Error: SQLSTATE[HY000] [2002] Connection timed outDB_AUTH ERROR 

Tried in Debian 9, with Mariadb 10.1 : same result 
Tried in Debian 10, with Mariadb 10.3 : same result 

Do You have any idea ? 
Thanks a lot

**Comment by K-razy** [comment]
Hello, here is the file attached.

[db_ossec.zip](https://github.com/jppo/OSSEC-GUI/files/4405785/db_ossec.zip)

**Comment by jppo** [comment]
I can't see any syntax errors which could explain the message, but when I see a "timeout" and "DB AUTH ERROR" I think about some network problem or a default IP address in the database users.
I would be interested by the solution ...
Regards
JP P

**Comment by K-razy** [comment]
Hello, 
Finally resolved the issue.
The thing is that, the amilogged.php is already linked to amilogged.php_auth after git clone.
So the db_auth.php file si called, and was not configured.
