### ISSUE TITLE
Dashboard Empty and no data in detail.php

### ISSUE THREAD

**Issue by K-razy** [jppo/OSSEC-GUI#3]
Hello, 

I succesfully installed ossec-gui first without authentication.
I created agents, and allow ossec to send alerts into into database.
The issue is the main page 'index.php' does not show any chart or any data
Columns Top Rule_ID, Top Loc and Rare In are blank with nothing inside.

But when i go to massmonitoring.php page i see events counted.
Do you have any idea ?

Attached screenshot of the issue.

Thanks in advance.

![index php](https://user-images.githubusercontent.com/62814529/89335409-44734700-d698-11ea-8b3f-d089af85e453.png)
![massmonitoring php](https://user-images.githubusercontent.com/62814529/89335412-45a47400-d698-11ea-8db5-cc21a5e06e75.png)

Best Regards

**Comment by jppo** [comment]
Hello,

As I can see on the screen no level is choosen, so I think that the system does not find any rows with "no level".in the database.
I said something in the doc for auth or noauth and about the link. I am sorry if it was not clear enough.
I hope that if you choose a level the related rows will appear.
I use every day to look at my small (very small) personnal datacenter with some VM's, mainly KVM.
Please keep me in touch ...
Regards
JP Pozzi

**Comment by K-razy** [comment]
Hello, 

Thanks for your quick answer.
Unfortunately, i'm not able to select one level, the only choice i have is : --

![image](https://user-images.githubusercontent.com/62814529/89341228-47bf0080-d6a1-11ea-9bb6-36e1be08a97f.png)

in detail.php is the same thing for level min and level max

I just checked in my database, levels are correctly stored 
![image](https://user-images.githubusercontent.com/62814529/89341962-61ad1300-d6a2-11ea-99c4-b97f65b4aee7.png)

Thanks in advance for your time.

Best Regards

**Comment by jppo** [comment]
The "levels" are extracted from the database (not history) with that SQL 
SELECT distinct(level) FROM ossec_base.signature ORDER BY level
and the radio button is done with that data ...
The "signature" table is probablu not OK. If you need one I can dump mine ...

Regards
JP P

**Comment by jppo** [comment]
I add a new file to the repository : "ossec.signature.gz" it is in "insert" simple format (one line for each row).

**Comment by K-razy** [comment]
Exactly, 
Signature table was entirely empty.
I found an issue opened in ossec-hids github

Thanks a lot for your dump it helped me a lot. 
i'm now able to see graphs and data are now available.
Thanks a lot for your reactivity.

Best Regards
